apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: image-cleanup
spec:
  schedule: "0 10 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: default
          serviceAccountName: default
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 0
          enableServiceLinks: true
          hostIPC: true
          hostNetwork: true
          hostPID: true
          restartPolicy: Nerver
          containers:
          - name: node-shell
            image: docker.io/alpine:3.13
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 30m
                memory: 16M
              requests:
                cpu: 30m
                memory: 16Mi
            securityContext:
              privileged: true
            command: ["nsenter"]
            args: ["-t", "1", "-m", "-u", "-i", "-n", "--", "docker", "image",  "prune", "--force"]
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: Never
